name: 'Forked update'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        target_sync_branch: master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: https://git.sr.ht/~cadence/bibliogram

        # Set test_mode true to run tests instead of the true action!!
        test_mode: false
      
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits updated"
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "No new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
